#!/bin/bash
# Constitution Sync Script
# Syncs the constitution from planning repo to code repositories

set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PLANNING_REPO="$SCRIPT_DIR/.."
PLANNER_REPO="$PLANNING_REPO/../cz.imcg.fast.planner"
OVYSLEDOVKA_REPO="$PLANNING_REPO/../cz.imcg.fast.ovysledovka"
ZEN_ORCH_REPO="$PLANNING_REPO/../cz.en.orch"

CONSTITUTION_SOURCE="$PLANNING_REPO/_bmad/_memory/constitution.md"

echo "===================================="
echo "Constitution Sync Script"
echo "===================================="
echo ""

# Check if constitution source exists
if [ ! -f "$CONSTITUTION_SOURCE" ]; then
  echo "❌ ERROR: Constitution source not found at $CONSTITUTION_SOURCE"
  exit 1
fi

# Extract version from constitution
VERSION=$(grep -E '^\*\*Version\*\*:' "$CONSTITUTION_SOURCE" | sed 's/.*: \([0-9.]*\).*/\1/')
echo "📄 Constitution Version: $VERSION"
echo ""

# Function to sync to a repository
# Usage: sync_to_repo <repo_path> <repo_name> <relative_target_path>
# Example: sync_to_repo "/path/to/repo" "my-repo" "src/.constitution.md"
sync_to_repo() {
  local repo_path=$1
  local repo_name=$2
  local relative_target=${3:-"src/.constitution.md"}
  local target_file="$repo_path/$relative_target"

  if [ ! -d "$repo_path" ]; then
    echo "⚠️  WARNING: Repository not found: $repo_name ($repo_path)"
    echo "   Skipping..."
    return
  fi

  # Create target directory if it doesn't exist
  mkdir -p "$(dirname "$target_file")"

  # Add sync header
  {
    echo "<!-- SYNCED FROM PLANNING REPOSITORY -->"
    echo "<!-- Source: cz.imcg.fast.allocations/_bmad/_memory/constitution.md -->"
    echo "<!-- DO NOT EDIT THIS FILE DIRECTLY - Changes will be overwritten -->"
    echo "<!-- To modify constitution, edit in planning repository and run repos/sync-constitution.sh -->"
    echo ""
    cat "$CONSTITUTION_SOURCE"
  } > "$target_file"

  echo "✅ Synced to $repo_name: $target_file"
}

# Sync to all repositories
sync_to_repo "$PLANNER_REPO"     "cz.imcg.fast.planner"     "src/.constitution.md"
sync_to_repo "$OVYSLEDOVKA_REPO" "cz.imcg.fast.ovysledovka" "src/.constitution.md"
sync_to_repo "$ZEN_ORCH_REPO"    "cz.en.orch"               "src/zen_orch/.constitution.md"

echo ""
echo "===================================="
echo "✅ Constitution sync complete!"
echo "===================================="
echo ""
echo "Next steps:"
echo "1. Review the synced files in code repositories"
echo "2. Commit the changes in each code repository"
echo "3. Update AGENTS.md in code repos to reference the synced constitution"
echo ""
